name: Deploy to Heroku

on:
  push:
    branches:
      - api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build, Push and Release a Docker container to Heroku.
        env:
           HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
           APP_NAME: ${{secrets.HEROKU_APP_NAME}}
        run: |
            cd ./WeEditPlatform
            docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
            heroku container:push web -a $APP_NAME
            heroku container:release web -a $APP_NAME